version: "3.8"

services:
  postgresdb:
    image: postgres
    hostname: metastore_db
    restart: always
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - /opt/postgres-data:/var/lib/postgresql/data
    networks:
      - datalake-net

  hive-metastore:
    image: 'starburstdata/hive:3.1.2-e.18'
    hostname: hive-metastore
    ports:
      - '9083:9083'
    restart: always
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://bronze/
 

      # Configs originais para MinIO (corretas)
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: admin123
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""

      # ✅ Necessário para funcionar com o `s3a://` no Hive/Trino
      FS_S3A_ENDPOINT: http://minio:9000
      FS_S3A_ACCESS_KEY: admin
      FS_S3A_SECRET_KEY: admin123
      FS_S3A_PATH_STYLE_ACCESS: "true"
      FS_S3A_CONNECTION_SSL_ENABLED: "false"

      # Extras (não alterar se não for usar GCP ou Azure)
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""

      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"

    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/9083"
    depends_on:
      - postgresdb
    networks:
      - datalake-net


  trino:
    image: 'trinodb/trino:400'
    hostname: trino-coordinator
    restart: always
    ports:
      - '8080:8080'
    working_dir: /usr/lib/trino
    volumes:
      - /opt/trino-config:/etc/trino
    depends_on:
      - hive-metastore
      - minio
    networks:
      - datalake-net

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - datalake-net

  superset-db:
    image: postgres:13
    container_name: superset-db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - superset_db:/var/lib/postgresql/data
    networks:
      - datalake-net

  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: supersecret
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
      ADMIN_FIRSTNAME: Superset
      ADMIN_LASTNAME: Admin
      ADMIN_EMAIL: admin@superset.com
      DATABASE_DIALECT: postgresql
      DATABASE_USER: superset
      DATABASE_PASSWORD: superset
      DATABASE_HOST: superset-db
      DATABASE_PORT: 5432
      DATABASE_DB: superset
    depends_on:
      - superset-db
    volumes:
      - superset_home:/app/superset_home
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin123 &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "
    networks:
      - datalake-net

volumes:
  superset_db:
  superset_home:

networks:
  datalake-net:
